[versions]
# libraries
annotations = "24.2.0"

# plugins
kotlin = "1.9.21"
changelog = "2.2.0"
gradleIntelliJPlugin = "1.17.2"
qodana = "0.1.13"
kover = "0.7.4"
kordex = "1.7.0-SNAPSHOT"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
kordex-annotations = { group = "com.kotlindiscord.kord.extensions", name = "annotations", version.ref = "kordex" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
